# Generated by Django 2.2.2 on 2019-06-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big5_openness', models.FloatField()),
                ('facet_adventurousness', models.FloatField()),
                ('facet_artistic_interests', models.FloatField()),
                ('facet_emotionality', models.FloatField()),
                ('facet_imagination', models.FloatField()),
                ('facet_intellect', models.FloatField()),
                ('facet_liberalism', models.FloatField()),
                ('big5_conscientiousness', models.FloatField()),
                ('facet_achievement_striving', models.FloatField()),
                ('facet_cautiousness', models.FloatField()),
                ('facet_dutifulness', models.FloatField()),
                ('facet_orderliness', models.FloatField()),
                ('facet_self_discipline', models.FloatField()),
                ('facet_self_efficacy', models.FloatField()),
                ('big5_extraversion', models.FloatField()),
                ('facet_activity_level', models.FloatField()),
                ('facet_assertiveness', models.FloatField()),
                ('facet_cheerfulness', models.FloatField()),
                ('facet_excitement_seeking', models.FloatField()),
                ('facet_friendliness', models.FloatField()),
                ('facet_gregariousness', models.FloatField()),
                ('big5_agreeableness', models.FloatField()),
                ('facet_altruism', models.FloatField()),
                ('facet_cooperation', models.FloatField()),
                ('facet_modesty', models.FloatField()),
                ('facet_morality', models.FloatField()),
                ('facet_sympathy', models.FloatField()),
                ('facet_trust', models.FloatField()),
                ('big5_neuroticism', models.FloatField()),
                ('facet_anger', models.FloatField()),
                ('facet_anxiety', models.FloatField()),
                ('facet_depression', models.FloatField()),
                ('facet_immoderation', models.FloatField()),
                ('facet_self_consciousness', models.FloatField()),
                ('facet_vulnerability', models.FloatField()),
                ('need_challenge', models.FloatField()),
                ('need_closeness', models.FloatField()),
                ('need_curiosity', models.FloatField()),
                ('need_excitement', models.FloatField()),
                ('need_harmony', models.FloatField()),
                ('need_ideal', models.FloatField()),
                ('need_liberty', models.FloatField()),
                ('need_love', models.FloatField()),
                ('need_practicality', models.FloatField()),
                ('need_self_expression', models.FloatField()),
                ('need_stability', models.FloatField()),
                ('need_structure', models.FloatField()),
                ('value_conservation', models.FloatField()),
                ('value_openness_to_change', models.FloatField()),
                ('value_hedonism', models.FloatField()),
                ('value_self_enhancement', models.FloatField()),
                ('value_self_transcendence', models.FloatField()),
            ],
            options={
                'ordering': (),
            },
        ),
    ]
